require 'sinatra'
require 'line/bot'
require 'sinatra/activerecord'
# require 'sinatra/activerecord/rake'
require './models'
require './src/hello'
require './src/line'
require './src/web'
require 'dotenv'
Dotenv.load
